version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - cd react_web
      - npm install
      - cd -
  build:
    commands:
      - cd react_web
      - npm run build
      - cd dst

artifacts:
  files:
    - bundle-main.js
    - index.html
  name: react_web_pack
