version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - cd react_web
      - npm install
      - cd -
  build:
    commands:
      - cd react_web
      - npm run build
      - cd -

artifacts:
  files:
    - react_web/dst/bundle-main.js
    - react_web/dst/index.html
  name: react_web_pack
